#ifndef __NETDEFINE__
#define __NETDEFINE__



namespace Net{
namespace Raw{
#pragma pack(1)


	
enum TcpFlag
{
	eCWR = 0x80,
	eACE = 0x40,
	eURG = 0x20,
	eACK = 0x10,
	ePSH = 0x08,
	eRST = 0x04,
	eSYN = 0x02,
	eFIN = 0x01
};


enum IcmpType
{
	eECHO_REPLY =0,
	eDISTINATION_UNREACHABLE =3,
	eSOURCE_QUENCH = 4,
	eREDIRECT = 5,
	eECHO_REQUEST = 8,
	eTIME_EXEEDED_FOR_A_DATAGRAM = 11,
	ePARAMETER_PROBLEM_ON_A_DATAGRAM = 12,
	eTIMESTAMP_REQUEST = 13,
	eTIMESTAMP_REPLAY = 14,
	eINFORMATION_REQUEST = 15,
	eINFORMATION_REPLY = 16,
	eADDRESS_MASK_REQUEST = 17,
	eADDRESS_MASK_REPLY = 18
};


enum IcmpCode
{
	eNETWORK_UNREACHABLE=0,
	eHOST_UNREACHABLE,
	ePROTOCOL_UNREACHABLE,
	ePORT_UNREACHABLE,
	eFRAGMENTATION_NEEDED_AND_DF_SET,
	eSOURCE_ROUTE_FAILED,
	eDESTINATION_NETWORK_UNKNOWN,
	eDESTINATION_HOST_UNKNOWN,
	eSOURCE_HOST_ISOLATED,
	eCOMMUNICATION_WITH_DESTINATION_NETWORK_ADMINISTRAIVELY_PROHIBITED,
	eCOMMUNICATION_WITH_DESTINATION_HOST_ADMINISTRAIVELY_PROHIBITED,
	eNETWORK_UNREACHABLE_FOR_TYPE_OF_SERVICE,
	eHOST_UNREACHABLE_FOR_TYPE_OF_SERVICE
};





#pragma pack()
} // namespace Raw
} // namespace Net


#endif
